### ISSUE TITLE
how to use .pyx in nms file

### ISSUE THREAD

**Issue by sadsearth** [liuwei16/CSP#9]
from nms.cpu_nms import cpu_nms
can't import correctly.
so i wonder how to compile in your code, and can you show the makefile

**Comment by hdjsjyl** [comment]
I meet the same problem, did you solve it? Thanks

**Comment by sadsearth** [comment]
I still don’t know how to solve yet, and I hope author will notice our problem.


发自我的iPhone

------------------ Original ------------------

**Comment by hdjsjyl** [comment]
@sadsearth , when you run the training of the code, how about the gpu utility, what is your gpu? Can you share training information as a reference? Thank you very much!

**Comment by sadsearth** [comment]
@liuwei16

**Comment by liuwei16** [comment]
@sadsearth @hdjsjyl sorry, the code for NMS is from py-faster-rcnn, you can follow https://github.com/rbgirshick/py-faster-rcnn to compile it by yourself.

**Comment by sadsearth** [comment]
@hdjsjyl Hi, did you solve it?  After following https://github.com/rbgirshick/py-faster-rcnn to compile the code, I still met
![](http://ww1.sinaimg.cn/large/006HWYRlgy1g2q7tskk0bj31b0102ti0.jpg)

**Comment by hdjsjyl** [comment]
@sadsearth , after compiling following the advice, my code does not have this problem again. Thanks

**Comment by msha096** [comment]
> @sadsearth , after compiling following the advice, my code does not have this problem again. Thanks

How did you solve it?

**Comment by soongyuu** [comment]
@hdjsjyl  How did you solve it?

**Comment by soongyuu** [comment]
@msha096 My solution is to copy all folders except nms under the py-faster-rcnn-master/lib path to the CSP-master/keras_csp path. Then, make!

**Comment by msha096** [comment]
> @msha096 My solution is to copy all folders except nms under the py-faster-rcnn-master/lib path to the CSP-master/keras_csp path. Then, make!

Did you solution work? what is your cuda and gcc version?
Thanks!

**Comment by soongyuu** [comment]
cuda:9.0  gcc:5.4

**Comment by msha096** [comment]
> cuda:9.0 gcc:5.4

Thanks, it works for me.

**Comment by zxinyang38** [comment]
@msha096 What is your solution, do I have to install gcc5.4?

**Comment by msha096** [comment]
> @msha096 What is your solution, do I have to install gcc5.4?

My solution is what soongyuu said. I installed gcc5.4, not sure if it is necessary.

**Comment by zxinyang38** [comment]
@msha096 好的，谢谢

**Comment by fengyuentau** [comment]
Following the advice from https://github.com/liuwei16/CSP/issues/9#issuecomment-488234679 and https://github.com/liuwei16/CSP/issues/9#issuecomment-492058883 and also the pull request https://github.com/liuwei16/CSP/pull/53#issue-304999591, the solution to get the nms module working with the minimum changes is:
1. install cython: `pip install cython`
2. enter `$CSP/keras_csp`, copy the following two files from https://github.com/rbgirshick/py-faster-rcnn/tree/master/lib:
    1. [Makefile](https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/Makefile)
    2. [setup.py](https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/setup.py), remove [line 113-118](https://github.com/rbgirshick/py-faster-rcnn/blob/781a917b378dbfdedb45b6a56189a31982da1b43/lib/setup.py#L113-L118) and [line 142-149](https://github.com/rbgirshick/py-faster-rcnn/blob/781a917b378dbfdedb45b6a56189a31982da1b43/lib/setup.py#L142-L149)
3. run `make` in `$CSP/keras_csp`

The nms module should work now.

**Comment by zhijianglu** [comment]
when i run make in keras_csp ,it comes python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 53, in locate_cuda
    for k, v in cudaconfig.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
how to slove this error?

**Comment by baiboat** [comment]
> when i run make in keras_csp ,it comes python setup.py build_ext --inplace
> Traceback (most recent call last):
> File "setup.py", line 58, in
> CUDA = locate_cuda()
> File "setup.py", line 53, in locate_cuda
> for k, v in cudaconfig.iteritems():
> AttributeError: 'dict' object has no attribute 'iteritems'
> Makefile:2: recipe for target 'all' failed
> make: *** [all] Error 1
> how to slove this error?

i got the same error,did you fixed that?

**Comment by xauat-liushipeng** [comment]
@soongyuu if your method must have cuda?   may i do it on cpu?

**Comment by ll490187880** [comment]
> > when i run make in keras_csp ,it comes python setup.py build_ext --inplace
> > Traceback (most recent call last):
> > File "setup.py", line 58, in
> > CUDA = locate_cuda()
> > File "setup.py", line 53, in locate_cuda
> > for k, v in cudaconfig.iteritems():
> > AttributeError: 'dict' object has no attribute 'iteritems'
> > Makefile:2: recipe for target 'all' failed
> > make: *** [all] Error 1
> > how to slove this error?
> 
> i got the same error,did you fixed that?

Python3.x do not support iteritems()，modify iteritems() to items() in the line 53

**Comment by Abel150** [comment]
How to compile it with windows 10?

**Comment by SouleTraveler** [comment]
> How to compile it with windows 10?

Have you solved it? I confused the same problem ethier.
